;; Set up the keyboard so the delete key on both the regular keyboard
;; and the keypad delete the character under the cursor and to the right
;; under X, instead of the default, backspace behavior.
(global-set-key [delete] 'delete-char)
(global-set-key [kp-delete] 'delete-char)
(global-set-key "\C-v" 'yank)
(custom-set-variables
 '(c-basic-offset 2)
 '(c-default-style "stroustrup")
 '(c-label-minimum-indentation 0)
 '(c-offsets-alist (quote ((block-open . +) (case-label . +) (inextern-lang . 0) (innamespace . 0))))
 '(c-tab-always-indent t)
 '(case-fold-search t)
 '(current-language-environment "English")
 '(fill-column 78)
 '(font-lock-auto-fontify t)
 '(font-lock-maximum-decoration t)
 '(font-lock-mode t nil (font-lock))
 '(font-lock-use-colors nil)
 '(font-lock-use-fonts t)
 '(indent-tabs-mode nil)
 '(line-number-mode t)
 '(load-home-init-file t t)
 '(make-backup-files nil)
 '(query-user-mail-address nil)
 '(require-final-newline t)
 '(tab-width 2)
 '(transient-mark-mode t)
 '(truncate-lines t)
(custom-set-faces
 '(default ((t (:family "Clean" :size "12pt"))) t))
(setq minibuffer-max-depth nil)
