MACRO(TRIBITS_SUBPACKAGE SUBPACKAGE_NAME)

  SET(SUBPACKAGE_FULLNAME ${SUBPACKAGE_NAME})
			 
  # To provide context for various macros
  SET(PACKAGE_NAME ${SUBPACKAGE_FULLNAME})

  SET(PARENT_PACKAGE_SOURCE_DIR "${PACKAGE_SOURCE_DIR}")
  SET(PARENT_PACKAGE_BINARY_DIR "${PACKAGE_BINARY_DIR}")

ENDMACRO()


#
# Postprocess after defining a subpackage
#

MACRO(TRIBITS_SUBPACKAGE_POSTPROCESS)

ENDMACRO()
